# Generated by Django 5.0.3 on 2025-08-27 12:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга'), ('series', 'Сериал'), ('game', 'Игра'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип источника')),
                ('title', models.CharField(max_length=200, verbose_name='Название источника')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор/Режиссер')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Чем выше вес, тем больше шанс показа цитаты', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Вес цитаты')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Дизлайки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes_app.source', verbose_name='Источник')),
            ],
        ),
    ]
