# Generated by Django 5.0.3 on 2025-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор цитаты'),
        ),
    ]
