# Generated by Django 5.0.3 on 2025-08-30 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_quote_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
